[[entries]]
from = "~/dotfiles/cargo/.cargo"
to = "~/.cargo"

[[entries]]
from = "~/dotfiles/local-bin/.local/bin"
to = "~/.local/bin"

[[entries]]
from = "~/dotfiles/zsh"
to = "~"

[[entries]]
from = "~/dotfiles/htop/.config/htop"
to = "~/.config/htop"

[[entries]]
from = "~/dotfiles/deepin-terminal-gtk/.config/deepin"
to = "~/.config/deepin"

[[entries]]
from = "~/dotfiles/gitconfig"
to = "~"